name: Build sdist

# on: [push, pull_request]
on: workflow_dispatch

jobs:
  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
     
      - name: Install libtiff
        run:  sudo apt-get install libtiff-dev libtiff6


      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-sdist
          path: dist/*.tar.gz
